interface=wlan0
driver=nl80211
# SSID/Pass overwritten by provision_wifi.sh on boot
ssid=Halo_SETUP
hw_mode=g
channel=6
wmm_enabled=0
macaddr_acl=0
auth_algs=1

# --- Security Settings ---
# Optional: 1 = Hidden SSID (User must scan QR code or type manual)
ignore_broadcast_ssid=0

# WPA2 Configuration
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_passphrase=halo_default